### ISSUE TITLE
gdal_fillnodata

### ISSUE THREAD

**Issue by bertt** [Geodan/terrain#1]
We use gdal_fillnodata to fill areas with nodata, but on larger nodata areas (like larger buildings or lakes) there is still nodata. What happens with those nodata areas? 

Maybe related to watermask extension https://github.com/Geodan/terrain/issues/4

**Comment by kamielverhelst** [comment]
Een groep studenten van de TU Delft heeft hier een mooi project over gedaan
- Repo: https://github.com/tudelft3d/geo1101.2020.ahn3
- Rapport: https://3d.bk.tudelft.nl/pdfs/synthesis/2020_ahn3_report.pdf

**Comment by bertt** [comment]
we have a parameter -m now in terrainwarp (default 100 pixels)
