### ISSUE TITLE
Test on AHN4

### ISSUE THREAD

**Issue by bertt** [Geodan/terrain#12]

**Comment by kamielverhelst** [comment]
The process (this version #17) runs on the server without errors.  The output (`tiles`) clearly misses the folders (zoomlevels) 9 and 10. I have the idea that a big part of the subfolders of level 8 is also missing. Could this be the large numbers issue again? 

The output directory (`tiles`) contains ~200.000 files and is around 100MB, 80MB when compressed.

The output looks great in a Cesium viewer! Especially natural areas such as dunes: 
![image](https://github.com/Geodan/terrain/assets/122441727/29164343-7fe3-4c4a-b5bf-3a1936d5eb41)



However, there are some issues, decribed below.

**Issue: terrain seems to not correspond to reality**
Especially considering the 0.5m resolution of the input imagery, the terrain does not seem very realistic on high zoom levels. See for example this football field: 
<img width="1269" alt="image" src="https://github.com/Geodan/terrain/assets/122441727/be03633e-4b26-4a1f-9d4f-c4e074c0a976">

**Issue: straight lines show wave patterns**
Straight features (like dikes) show up wavy in the tiles. Here is an example of the Afsluitdijk:
![image](https://github.com/Geodan/terrain/assets/122441727/f036b6b7-3d92-437c-a76d-4368a1066a1d)

**Issue: missing tiles for South NL**
There seems to be a big portion of tiles entirely missing, mostly in the south of the Netherlands. Possibly, the cause for this is an incomplete set of AHN4 tiles. 

![image](https://github.com/Geodan/terrain/assets/122441727/23506652-4970-4506-a8ad-649ad9dcf5bd)

**Comment by bertt** [comment]
Maastricht sample see https://geodan.github.io/terrain/samples/maastricht/ (created with -m 1000, levels 0-15)
