### ISSUE TITLE
tiler : ERROR 1: Too many threads [...] or too many proxy datasets are opened in a cascaded way. 

### ISSUE THREAD

**Issue by Doctor-Who** [Geodan/terrain#42]
Hi,

I've got an issue when trying to use tiler part.
Trying to generate mesh on french data name RGE Alti 1m on Hauts-de-France administrative boundaries region (about 32 000 km²)

Launch parameters : `podman run --name geodan_1_2 -v $(pwd):/data -it geodan/terraintiler -j 10 -s 20`
First I've set -j to 80 but I understand it was quite huge but even with -j 10 or no setting to use default one, I've got these message : 
 
```ERROR 1: Too many threads are running for the current value of the dataset pool size (100).
or too many proxy datasets are opened in a cascaded way.
Try increasing GDAL_MAX_DATASET_POOL_SIZE.
```

Thanks for your help

**Comment by bertt** [comment]
hmm never seen this error, did you process something like https://github.com/bertt/corsica_gr20/tree/main/cesium ?

**Comment by Doctor-Who** [comment]
Nearly same method.
Download asc files
Make a vrt with gdal wrap
Generate a single tif file with gdal translate as bilinear and epsg 4326 instead 2154
Launch your first process docker image
Then launch the tiler part.

**Comment by bertt** [comment]
maybe it's the single tif file? Tiler can use vrt as input. In the warp process a vrt is generated.

**Comment by Doctor-Who** [comment]
Ok I will try by only convert asc to tif without combing it. I was worried about wrapping tiles and got some holes or overlay when reprojecting

**Comment by Doctor-Who** [comment]
I've try other approach but I got an error when trying to generate VRT.
Probably because I've got too much tiles ? 

```
Terrain tiler 1.1 - Warp
Start: Wed Aug 23 07:59:54 UTC 2023
Temp directory: tmp
Fillnodata maxdistance: 1000
Jobs: 60
tmp directory created.
used s_srs: EPSG:2154
Start processing 32990 GeoTIFFS...
100% 32990:0=0s ./RGEALTI_FXX_0790_6980_MNT_LAMB93_IGN69.tif                                                                                                                                                                                                               
Building virtual raster tmp/ahn.vrt...
/process.sh: line 124: /usr/bin/gdalbuildvrt: Argument list too long
VRT created: tmp/ahn.vrt
End: Wed Aug 23 08:13:40 UTC 2023
Elapsed time: 826 seconds.
End of processing
```

Peraphs it could be fix by using  option -input_file_list with gdalbuildvrt ?

**Comment by bertt** [comment]
yeah could be many files, how many are there? What happens with a subset?

**Comment by Doctor-Who** [comment]
32990 GeoTIFFS ^^
On a smaller subset it works.

I will make manually the VRT and continue process to see what happen.
On wrap step, each tiles are reproject and nodata filled, is there a risk that some part had some overlap or holes between tiles ?
